#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.20f1_cef3e6c0c622"
#define UNITY_VERSION_FULL_NICE "2018.2.20f1 (cef3e6c0c622)"
#define UNITY_VERSION_BLD 13562854
#define UNITY_VERSION_DATE 1544175796
#define UNITY_VERSION_WIN "2018.2.20.13562854"
#define UNITY_VERSION_BRANCH "2018.2/staging"
